### ISSUE TITLE
When i just import the openpnm,NameError("name 'μSymbol' is not defined")

### ISSUE THREAD

**Issue by Shylcok** [PMEAL/OpenPNM#1322]
this is the Traceback,(is that happened cos by my Chinese dir name?):
Traceback (most recent call last):
  File "C:\Users\11985\Anaconda3\lib\site-packages\unyt\_parsing.py", line 89, in parse_unyt_expr
    unit_expr, global_dict=global_dict, transformations=unit_text_transform
  File "C:\Users\11985\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py", line 894, in parse_expr
    return eval_expr(code, local_dict, global_dict)
  File "C:\Users\11985\Anaconda3\lib\site-packages\sympy\parsing\sympy_parser.py", line 807, in eval_expr
    code, global_dict, local_dict)  # take local objects in preference
  File "<string>", line 1, in <module>
NameError: name 'μSymbol' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/11985/PycharmProjects/数据处理/src/python/__init__.py", line 13, in <module>
    import openpnm as op
  File "C:\Users\11985\Anaconda3\lib\site-packages\openpnm\__init__.py", line 59, in <module>
    from . import core
  File "C:\Users\11985\Anaconda3\lib\site-packages\openpnm\core\__init__.py", line 106, in <module>
    from .Base import Base
  File "C:\Users\11985\Anaconda3\lib\site-packages\openpnm\core\Base.py", line 1, in <module>
    import unyt
  File "C:\Users\11985\Anaconda3\lib\site-packages\unyt\__init__.py", line 75, in <module>
    from unyt import unit_symbols
  File "C:\Users\11985\Anaconda3\lib\site-packages\unyt\unit_symbols.py", line 33, in <module>
    _namespace[_alt_name] = _Unit(_canonical_name, registry=_registry)
  File "C:\Users\11985\Anaconda3\lib\site-packages\unyt\unit_object.py", line 173, in __new__
    unit_expr = parse_unyt_expr(unit_expr)
  File "C:\Users\11985\Anaconda3\lib\site-packages\unyt\_parsing.py", line 96, in parse_unyt_expr
    raise UnitParseError(msg)
unyt.exceptions.UnitParseError: Unit expression 'µm' raised an error during parsing:
NameError("name 'μSymbol' is not defined")

**Comment by jgostick** [comment]
The error is due to an outdated dependency...I solved the issue myself a few weeks ago, but forget exactly what the problem was. 

Try updating *sympy* and *unyt*.  TOpen your conda prompt and type:

```
C:\pip install --upgrade unyt
C:\conda update sympy
```

**Comment by Shylcok** [comment]
thank for all your help




------------------ 原始邮件 ------------------
发件人: "jgostick"<notifications@github.com>; 
发送时间: 2019年8月16日(星期五) 凌晨4:10
收件人: "PMEAL/OpenPNM"<OpenPNM@noreply.github.com>; 
抄送: "王佳宇"<1198509739@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [PMEAL/OpenPNM] When i just import the openpnm,NameError("name 'μSymbol' is not defined") (#1322)




The error is due to an outdated dependency...I solved the issue myself a few weeks ago, but forget exactly what the problem was.
 
Try updating sympy and unyt.  TOpen your conda prompt and type:
 C:\pip install --upgrade unyt C:\conda update sympy
