### ISSUE TITLE
Installation problem with openpnm

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2181]
Hello. I followed the installation guideline [[here](http://openpnm.org/userguide/installation.html)](url) using Anaconda but I haven't been able to install yet. 

Can somebody please help?

This is the error I am getting.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\__init__.py", line 64, in <module>
    from . import algorithms
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\__init__.py", line 13, in <module>
    from .GenericTransport import GenericTransport
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 3, in <module>
    import scipy.sparse.linalg
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.
```

**Comment by debanik1** [comment]
This is the error I am getting.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\__init__.py", line 64, in <module>
    from . import algorithms
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\__init__.py", line 13, in <module>
    from .GenericTransport import GenericTransport
  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 3, in <module>
    import scipy.sparse.linalg
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "C:\Users\deban\anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.

**Comment by ma-sadeghi** [comment]
I was able to install `openpnm` on my machine. Just to make sure you can do the same, do the followings:

1. Create a fresh virtual environment (called test) so if you have any broken dependencies, it's not going to affect your installation
```
conda create -n test python=3.8
```
2. Activate the test environment
```
conda activate test
```
3. Install `openpnm`
```
conda install openpnm
```
4. Test your installation
```
python -c "import openpnm"
```

If you were able to run the last step with no errors, chances are that there might be something wrong with your `scipy` installation in your default conda environment. One fix could be to update all packages (before, make sure to activate your `base` environment, since we're currently inside `test`.):
```
conda update --all
```

Let me know if it fixes you problem.

**Comment by debanik1** [comment]
> I was able to install `openpnm` on my machine. Just to make sure you can do the same, do the followings:
> 
>     1. Create a fresh virtual environment (called test) so if you have any broken dependencies, it's not going to affect your installation
> 
> 
> ```
> conda create -n test python=3.8
> ```
> 
>     2. Activate the test environment
> 
> 
> ```
> conda activate test
> ```
> 
>     3. Install `openpnm`
> 
> 
> ```
> conda install openpnm
> ```
> 
>     4. Test your installation
> 
> 
> ```
> python -c "import openpnm"
> ```
> 
> If you were able to run the last step with no errors, chances are that there might be something wrong with your `scipy` installation in your default conda environment. One fix could be to update all packages (before, make sure to activate your `base` environment, since we're currently inside `test`.):
> 
> ```
> conda update --all
> ```
> 
> Let me know if it fixes you problem.

Thanks for the inputs. I reinstalled numpy and scipy and it's working now.
