### ISSUE TITLE
Could not find module 'mkl_rt.dll' when calling alg.run()

### ISSUE THREAD

**Issue by debanik1** [PMEAL/OpenPNM#2184]
I get the following error when trying to run [Tutorial 1](https://github.com/PMEAL/OpenPNM/blob/dev/examples/tutorials/intro_to_openpnm_basic.ipynb) using alg.run().

```python
Traceback (most recent call last):

  File "C:\Users\deban\.spyder-py3\Tutorial.py", line 103, in <module>
    alg.run()

  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\ReactiveTransport.py", line 159, in run
    x = self._run_reactive(x0)

  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\ReactiveTransport.py", line 361, in _run_reactive
    self[quantity] = x = self._solve(x0=x) * w + x * (1 - w)

  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 621, in _solve
    x = solver(A, b, atol=atol, rtol=rtol, max_it=max_it, x0=x0)

  File "C:\Users\deban\anaconda3\lib\site-packages\openpnm\algorithms\GenericTransport.py", line 679, in solver
    import pypardiso

  File "C:\Users\deban\anaconda3\lib\site-packages\pypardiso\__init__.py", line 4, in <module>
    from .scipy_aliases import spsolve, factorized

  File "C:\Users\deban\anaconda3\lib\site-packages\pypardiso\scipy_aliases.py", line 9, in <module>
    pypardiso_solver = PyPardisoSolver()

  File "C:\Users\deban\anaconda3\lib\site-packages\pypardiso\pardiso_wrapper.py", line 66, in __init__
    self.libmkl = ctypes.CDLL('mkl_rt.dll')

  File "C:\Users\deban\anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)

FileNotFoundError: Could not find module 'mkl_rt.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by jgostick** [comment]
did you install openpnm with pip or conda?  If the former then perhaps your pardiso installation is not present.  You can fix this with ``conda install pypardiso``

**Comment by debanik1** [comment]
> did you install openpnm with pip or conda? If the former then perhaps your pardiso installation is not present. You can fix this with `conda install pypardiso`

I installed with pip. When I tried to install with conda, I get the following error: 
```python
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pypardiso
```

**Comment by jgostick** [comment]
oops!  I forgot to add the channel info to my suggestion.  Try: ``conda install -c conda-forge pypardiso``.

**Comment by debanik1** [comment]
> oops! I forgot to add the channel info to my suggestion. Try: `conda install -c conda-forge pypardiso`.

Thanks. It's working as of now.
