### ISSUE TITLE
objs.remove_model is deprecated but still used in a geometry class

### ISSUE THREAD

**Issue by islah** [PMEAL/OpenPNM#300]
2015-02-06 14:15:51,844 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/islah/Documents/OpenPNM-develop/article recreation/gostick_recreation.py", line 13, in <module>
    geo = OpenPNM.Geometry.SGL10(network=sgl,pores=Ps,throats=Ts,name='geo')
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Geometry/__SGL10__.py", line 23, in __init__
    self._generate()
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Geometry/__SGL10__.py", line 32, in _generate
    self.remove_model('pore.seed')
AttributeError: 'SGL10' object has no attribute 'remove_model'

**Comment by islah** [comment]
when I run the gostick_recreation.py again after removing all commands using remove_model(), I got another error:
2015-02-06 14:30:14,375 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,376 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,379 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,381 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,382 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,382 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,387 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,392 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,392 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,393 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,410 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,410 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,411 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,415 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,415 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:14,600 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
2015-02-06 14:30:14,614 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
2015-02-06 14:30:14,626 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
2015-02-06 14:30:14,627 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
2015-02-06 14:30:14,691 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
2015-02-06 14:30:14,724 | WARNING  | root.regenerate | This method is deprecated, use obj.models.regenerate()
seq = 0.0 Seq out of 91.0 total sequences
2015-02-06 14:30:15,379 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:15,381 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:15,384 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
2015-02-06 14:30:15,386 | WARNING  | root.add_model | This method deprecated, use obj.models.add()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
    execfile(filename, namespace)
  File "/home/islah/Documents/OpenPNM-develop/article recreation/gostick_recreation.py", line 114, in <module>
    Stokes_alg_single_phase_air = OpenPNM.Algorithms.StokesFlow(name='Stokes_alg_single_phase_air',network=sgl,phase=air)
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Algorithms/__StokesFlow__.py", line 42, in __init__
    super(StokesFlow,self).__init__(**kwargs)
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Algorithms/__GenericLinearTransport__.py", line 29, in __init__
    super(GenericLinearTransport,self).__init__(**kwargs)
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Algorithms/__GenericAlgorithm__.py", line 41, in __init__
    super(GenericAlgorithm,self).__init__(**kwords)
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Base/__Core__.py", line 43, in __init__
    self.controller = ctrl
  File "/home/islah/Documents/OpenPNM-develop/OpenPNM/Base/__Core__.py", line 108, in _set_ctrl
    raise Exception('An object with that name is already present in simulation')
Exception: An object with that name is already present in simulation

**Comment by jgostick** [comment]
The first of the above issues, and the one referred to in the title, is now fixed.  I have gone in an updated all the subclassed Geometries included with OpenPNM.  There are still not doubt some instances of them in the documentation and examples, but these will have to wait.
